### ISSUE TITLE
Add support for google-java-format 1.2

### ISSUE THREAD

**Issue by mhernand40** [sherter/google-java-format-gradle-plugin#14]
Currently, the latest version of google-java-format is [1.2](https://github.com/google/google-java-format/releases/tag/google-java-format-1.2). It would be nice to add support for it.

**Comment by sherter** [comment]
I don't have any issues when setting [`toolVersion`](https://github.com/sherter/google-java-format-gradle-plugin#extended-usage) to `1.2`. Could you provide more details about the problems you are facing?

**Comment by mhernand40** [comment]
No problems at the moment. Just figured why not use the "latest and greatest"? I'm sure this is super low priority if it works just fine as is. Unfortunately, I don't believe there are release notes that show the improvements made in 1.2.

**Comment by sherter** [comment]
Well, then just set `toolVersion` to `1.2` if you want to use the "latest and greatest"?!

**Comment by mhernand40** [comment]
Sounds good to me. Didn't realize it was that simple :slightly_smiling_face:.

Thank you for referencing the issue that warranted the release of v2 and thank you for creating this plugin. It's super useful!
