### ISSUE TITLE
Since v1.2 google-java-format is compiled for java 8

### ISSUE THREAD

**Issue by sherter** [sherter/google-java-format-gradle-plugin#15]
I'd like to stay java 7 compatible, but versions newer than google-java-format v1.1 won't run on jvm 7.
TODO: Investigate if someone is relying on java 7 compatibility. Otherwise we might as well compile for java 8 ourselves.

**Comment by tylerbenson** [comment]
Can we get an updated release?  1.1 is getting pretty old at this point.  1.4 is already out. If anyone needs java 7 compatibility, they should stay on the 0.6 version of the plugin.

**Comment by sherter** [comment]
@tylerbenson If you want to use a different version of google-java-format, adjust your `build.gradle` (as described in the README):
```java
googleJavaFormat {
  toolVersion = '1.4'
}
```
This issue has nothing to do with what you are describing...

**Comment by tylerbenson** [comment]
Ok. Apologies for the misunderstanding.

**Comment by sherter** [comment]
https://github.com/sherter/google-java-format-gradle-plugin/commit/4a58e7778b6c553efbed5863bbdde54d3f661ba5
