### ISSUE TITLE
custom line length

### ISSUE THREAD

**Issue by ShikherVerma** [sherter/google-java-format-gradle-plugin#17]
hey I wanted to increase the line length to 150 instead of 80. Can I do that without forking or if I have to fork then where do I make the change
thanks

**Comment by sherter** [comment]
The formatting is done by [google-java-format](https://github.com/google/google-java-format), which doesn't support setting a custom line length. You _could_ create your own [Formatter Factory](https://github.com/sherter/google-java-format-gradle-plugin/blob/master/subprojects/format/src/main/groovy/com/github/sherter/googlejavaformatgradleplugin/format/FormatterFactory.java) and use reflection to change [this constant](https://github.com/google/google-java-format/blob/4174d878b36159a8efec949e95531d6cc1276393/core/src/main/java/com/google/googlejavaformat/java/JavaFormatterOptions.java#L32) before instantiating the Formatter, but that would be a really dirty hack. There is [this PR](https://github.com/google/google-java-format/pull/57), but I don't think it will be merged (as it is against their no-configurability-policy).

**Comment by ShikherVerma** [comment]
Cool, thanks for the quick response.
