### ISSUE TITLE
Version 0.6 of google-java-format-gradle-plugin is not tested against version 1.3 of google-java-format.

### ISSUE THREAD

**Issue by Bwvolleyball** [sherter/google-java-format-gradle-plugin#22]
Upgrade newer versions of this plugin for the most recent versions of the google-java-format.

I realize you desire to stay Java 7 compatible, however, if Google has dropped support of Java 7 after a certain version of their format, then this plugin should as well (although in the README there can (and should) be a section dedicated to describing which version of the plugin supports what. i.e. v0.6 is the latest version that supports Java 7, v0.7 only supports Java 8 etc.)

This is a good tool, but I want to make sure I can use the latest version of google-java-format, and that it is supported by this tool because this tool is a great enforcer!

**Comment by sherter** [comment]
This plugin _is_ compatible with the most recent releases of google-java-format. The warning is probably a bit misleading, but I didn't want to just crash with a weird ClassNotFoundException (or something similar) if the API of google-java-format changes. The warning should probably only be printed if something goes actually wrong when instantiating the formatter (note to myself//TODO).

The Java 7/8 discussion has nothing to do with being able to support new versions of google-java-format. Even if this plugin is compiled to target Java 7 VMs, you should be able to run it on a Java 8 VM (with `toolVersion` set to a version of google-java-format that is target at Java 8+).

**Comment by Bwvolleyball** [comment]
Cool, that works for me, and thanks for explaining what the warning meant a little more!
