### ISSUE TITLE
Only sources from first project in multi-project build formatted

### ISSUE THREAD

**Issue by pettermahlen** [sherter/google-java-format-gradle-plugin#25]
I've got a multi-project build where I'd like to use this plugin. However, it seems like only sources from the one sub-project that gets a task of type `com.github.sherter.googlejavaformatgradleplugin.GoogleJavaFormat` are included. So:

1. I have Java (and/or Android sources) in sub-projects A and B
1. The `settings.gradle` file includes both A and B in the build.
1. When I run `./gradlew -i :B:format`, the output indicates that files in A are formatted.

I've tried changing the order of includes, but that doesn't change anything - it seems like the first project that gets configured determines which source set gets included.

I've tried (for hours) to figure out if I'm doing something wrong, but no matter what I do, I don't seem to be able to find a way to solve this. How should this plugin be used in a multi-project build, where not all projects have Java files?

**Comment by pettermahlen** [comment]
BTW, this is the output of `./gradlew --version`:

```
------------------------------------------------------------
Gradle 4.1-rc-1
------------------------------------------------------------

Build time:   2017-07-20 15:22:15 UTC
Revision:     e9f4cb3be4b0a16506ad54b44485b7f0862f6c59

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_144 (Oracle Corporation 25.144-b01)
OS:           Mac OS X 10.13.1 x86_64
```

**Comment by sherter** [comment]
Try to apply the plugin (only) to the root project. It'll pickup all 
> *.java files in the project directory (and recursivly all subdirectories, excluding files in a (sub)project’s buildDir)

It shouldn't behave that weird though. If the workaround solves your problem, I'll leave this issue open for further investigation.

**Comment by pettermahlen** [comment]
Running it in the root seems to work, thanks for that! Do you have some advice on how to best hook it into the workflow? Previously, we had it set up to run before compilation in each Java sub-project, and in the 'preBuild' stage of Android sub-projects. We'd like to ensure that formatting 'just happens' as a part of the normal build.

**Comment by sherter** [comment]
> Previously, we had it set up to run before compilation in each Java sub-project, and in the 'preBuild' stage of Android sub-projects. We'd like to ensure that formatting 'just happens' as a part of the normal build.

If that's what you want, then your solution seems reasonable?!

**Comment by pettermahlen** [comment]
Yes, but the root project is now where the format task is, and I'm not sure how best to add dependencies so that the 'format' task in the root runs before any compilation task in sub-projects.

**Comment by sherter** [comment]
If I understood correctly, you previously had something like
```
tasks.assemble.dependsOn tasks.googleJavaFormat
```
in the subprojects' `build.gradle`, right?

Change that to
```
tasks.assemble.dependsOn rootProject.tasks.googleJavaFormat
```
and you should be good to go. Or am I missing something?

**Comment by pettermahlen** [comment]
That does work, I had to do some magic to handle the fact that Android projects are different than Java projects, so I've now got this in the root build.gradle:

```
   afterEvaluate { proj ->
        if (isAndroidProject(proj)) {
            // some more android specifics..
            android.libraryVariants.all { variant ->
                variant.javaCompiler.dependsOn(rootProject.tasks.format)
            }
        } else if (proj.plugins.findPlugin('java-library')) {
            proj.tasks.compileJava.dependsOn(rootProject.tasks.format)
        }
    }
```

Thanks for the help! I'm finding it hard to figure out my way around Gradle...
