### ISSUE TITLE
[Question] Detected syntax errors

### ISSUE THREAD

**Issue by rafasf** [sherter/google-java-format-gradle-plugin#28]
I recently added the plugin to a few projects and in two of those I get _"Detected Java syntax errors in the following files (you can...)"_ and the list includes all the files in the codebase.

### Some info
Plugin Version: 0.7.1
fileStates.txt has contents like: `path/to/file.java,1536345048000000000,738,INVALID`

### Attempts
* Change file encoding (to ensure UTF-8)
* Run a file at time

**But**, if I download `google-java-format-all-deps.jar` and run against the same files it works fine.

Any tips on what could be wrong or how I can get more insight on what happened?

**Comment by rafasf** [comment]
I'm using the defaults from 0.7.1. Both tools are under the same JDK and no extra options were used when I ran directly with the tool.

There is file I can share with you and it would probably be better if I sent you as an attachment to try to preserve most of its state. Where can I sent it?

**Comment by sherter** [comment]
sim.herter@gmail.com I'll look at it tomorrow then.

**Comment by sherter** [comment]
I'm sorry, but I cannot reproduce the error. Works as expected on my linux machine. Can you check whether the error is the same for mac/windows/linux?

**Comment by rafasf** [comment]
Thanks for looking into it. I will investigate a bit more.
