### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by gabrielittner** [sherter/google-java-format-gradle-plugin#3]
Using the plugin on an Android project will do nothing because the Android Gradle plugin has it's own `sourceSets`. I've created a quick test implementation of Android support [over here](https://github.com/gabrielittner/google-java-format-gradle-plugin/commit/d54ffff5bec531df6c5485b412309fd6814b15b2).

**Comment by sherter** [comment]
There is no documentation yet, but the current snapshot version already supports adding custom sources to the predefined `googleJavaFormat` task or even define your own task:

```groovy
tasks.googleJavaFormat {
  // something like this should work
  source(project.android.sourceSets.collect { it.sourceSet.java.sourceFiles })
  // Ant-style include/exclude patterns are also supported
  // source '.'
  // include '**/*.java
}

task format(type: GoogleJavaFormat) {
  source(project.android.sourceSets.collect { it.sourceSet.java.sourceFiles })
}
```

I can imagine different solutions to this problem (or combinations of them):
- Include all `**/*.java` files by default in the predefined `googleJavaFormat` task. Specific files can still be excluded with an `exclude` pattern.
- Provide methods like `javaSourceSets()` and `androidJavaSourceSets()` that can be passed to the `source` method of the task (similar to `jcenter()` and `mavenCentral()`).
- Just do what you did and don't think to much about it :wink: 

I tend towards solution 1, which also solves the problem of not having to apply the plugin to all subprojects and execute the task for each subproject individually. Do you see any problems with that? Or do you have another suggestion?

**Comment by sherter** [comment]
Maybe we should leave out the `build/` directory though, to not reformat generated source files...

**Comment by gabrielittner** [comment]
I don't see a problem with solution 1. It also has the advantage of not depending on the Android gradle plugin.
