### ISSUE TITLE
Formatting with plugin misses some files

### ISSUE THREAD

**Issue by msridhar** [sherter/google-java-format-gradle-plugin#33]
I have a case where running `./gradlew goJF` doesn't format all the source files.  Repro steps:

```bash
git clone https://github.com/wala/WALA.git
cd WALA
git checkout 564609f29817d0133b03b08b713cb61cc04f460f
# this will take a while due to initial build setup
./gradlew goJF
# this next command succeeds
./gradlew verGJF
rm -r build/google-java-format
# this one fails
./gradlew verGJF
```

Maybe something is off in the caching done under `build/google-java-format`?

**Comment by sherter** [comment]
The caching only works properly when formatting is idempotent, i.e. formatting already formatted files
doesn't change them anymore. This, however, seems not to be the case for some files in your project.
Please report this bug to the [google-java-format project](https://github.com/google/google-java-format). Thanks!

**Comment by msridhar** [comment]
Thanks a lot for taking a look!  Digging a bit I think this is google/google-java-format#211.  If it's not I'll submit a new issue on GJF.  Thanks again!
