### ISSUE TITLE
android 

### ISSUE THREAD

**Issue by nithin-aktivolabs** [sherter/google-java-format-gradle-plugin#34]
I am using the sherter gradle plugin in my android project. I want to use it in pre-commit script file. 

I added the plugin in gradle like this,
```

buildscript {
    repositories {
        jcenter()
        maven { url "https://plugins.gradle.org/m2/" }
    }

    dependencies {
        classpath 'gradle.plugin.com.github.sherter.google-java-format:google-java-format-gradle-plugin:0.5'
    }
}
```

in pre-commit file,

`./gradlew verifyGJF`

is not working, if I go to project root directory, then it is fine, it is working. My script file is in a folder called "scripts". Please help to make this run

**Comment by sherter** [comment]
Read the manual: https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks
You may want to use the [provided pre-commit hook script](https://github.com/sherter/google-java-format-gradle-plugin/blob/master/contrib/pre-commit)
