### ISSUE TITLE
Ignore failures on build

### ISSUE THREAD

**Issue by alexprut** [sherter/google-java-format-gradle-plugin#39]
It is possible to just print a `Warning` in case of not formatted properly files instead of failing the build? Is it possible to configure/override this behavior?

According to this class https://github.com/sherter/google-java-format-gradle-plugin/blob/master/src/main/groovy/com/github/sherter/googlejavaformatgradleplugin/VerifyGoogleJavaFormat.groovy#L23 it doesn't seem to be possible?

**Comment by sherter** [comment]
It _is_ possible and you actually found exactly the line that makes it possible. Just set that property to `true` (`false` is only the default value). In case you're using the default task it would be something like `tasks.verifyGoogleJavaFormat.ignoreFailures = true`

**Comment by alexprut** [comment]
Thanks @sherter ,  solved the issue.
