### ISSUE TITLE
Planned features for v0.3 

### ISSUE THREAD

**Issue by sherter** [sherter/google-java-format-gradle-plugin#4]
- [x] Improved logging (ad508105981b177e80c6c15bf64232c17bf6ca28, c948cef6f763df015089357176e1bdd9404b4249)
- [x] Performance: cache results of verification tasks (863a12a51cbb01fefd7b4cb78c21734d940540f3)
- [x] support for formatter options (995f659fa5cf3f305b8a046ecad42a93068f5bc8 and others)

**Comment by tbroyer** [comment]
> support for formatter options

:+1: At least provide option to sort imports (and maybe sort by default BTW)

**Comment by sherter** [comment]
> :+1: At least provide option to sort imports (and maybe sort by default BTW)

I started to work on this, but it seems like [sorting imports is broken in google-java-format](https://github.com/google/google-java-format/issues/42)

**Comment by tbroyer** [comment]
I see you're still defaulting to 0.1-alpha, have you tried with the recent 1.0?

**Comment by sherter** [comment]
Yes, I tried it with 1.0. There is no options API in 0.1-alpha.

**Comment by sherter** [comment]
I thought about options support again and I think I want to follow the idea of google-java-format and provide as little configuration options as possible. For now I'm going to provide only the `style` option (`'AOSP'/'GOOGLE'`). A Javadoc formatter is turned on by default (`ECLIPSE` for `1.0`). It should be easy now to add more options later, if someone has an actual use case.

@tbroyer I will also turn on imports sorting by default when https://github.com/google/google-java-format/issues/42 is resolved. Do you have a use case for turning it off?

**Comment by tbroyer** [comment]
No, my concern was being able to turn it on, not off ;-)
