### ISSUE TITLE
Can you upgrade to the latest 1.7 GJF? Thanks

### ISSUE THREAD

**Issue by duke-cliff** [sherter/google-java-format-gradle-plugin#40]
https://github.com/google/google-java-format

Because we use both your gradle-plugin and intellij plugin. https://plugins.jetbrains.com/plugin/8527-google-java-format

Recently we believe intellij plugin just upgraded to 1.7 GJF. And we are having issues with gradle-plugin reports unformatted files while intellij reports formatted.

We want to line up the two. Thanks

**Comment by sherter** [comment]
Do it yourself:
googleJavaFormat {
  toolVersion = '1.7'
}
https://github.com/sherter/google-java-format-gradle-plugin#extended-usage

**Comment by duke-cliff** [comment]
oh, didn't realize this setting. Thanks~!
