### ISSUE TITLE
Property 'ignoreFailures' has redundant getters

### ISSUE THREAD

**Issue by iboyperson** [sherter/google-java-format-gradle-plugin#41]
Upon running with gradle with `--warning-mode all` we get the warning `Property 'ignoreFailures' has redundant getters: 'getIgnoreFailures()' and 'isIgnoreFailures()'. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0`. There is no immediate urgency to this but should be fixed by 7.0

**Comment by sherter** [comment]
Thanks for reporting this!
