### ISSUE TITLE
Document how to run goJF before Gradle build task

### ISSUE THREAD

**Issue by jimshowalter** [sherter/google-java-format-gradle-plugin#44]
We wired https://github.com/sherter/google-java-format-gradle-plugin into our project per the readme.

We also wired in a pre-commit hook to run the plugin before committing, which ensures that all of the code in a changelist is formatted before pushing it, which avoids errors in Jenkins when we run the verGJF task.

But we have to keep remembering to run goJF locally before running ./gradlew build, or the build fails with formatting errors.

We worked around this by adding the https://plugins.jetbrains.com/plugin/8527-google-java-format and https://plugins.jetbrains.com/plugin/7642-save-actions plugins for IntelliJ, enabling the google-java-format plugin, and configuring the save-actions plugin to format on save.

But that's a lot of extra configuration a developer has to remember to go through, plus it means they can't format code the way they want while working on it, and only have it be reformatted at the point of build or commit.

We'd prefer an all-Gradle solution, so that the goJF task is run before the build task (and before the verGJF task, which is already bound to the build task by the google-java-format Gradle plugin).

We couldn't figure out how to do that. Does someone else know?

Also asked at https://stackoverflow.com/questions/61033598/how-can-i-configure-gradle-google-java-format-plugin-to-run-gojf-in-the-build-st

**Comment by jimshowalter** [comment]
StackOverflow to the rescue! All it takes is adding this after configuring the plugin:

verifyGoogleJavaFormat.dependsOn(tasks.googleJavaFormat)

It would be helpful if you'd add that to your readme.

**Comment by sherter** [comment]
I don't see the point of having a verification task that can never fail, but I'm glad you figured out how to achieve it. Task dependencies are a fundamental concept in Gradle and not specific to this plugin, so I would rather not document this specific use case explicitly.
