### ISSUE TITLE
Trying again about documenting how to always run your formatter before building

### ISSUE THREAD

**Issue by jimshowalter** [sherter/google-java-format-gradle-plugin#45]
You closed https://github.com/sherter/google-java-format-gradle-plugin/issues/44, but in your comments when you closed it, it's not clear to me that you understood why I opened it.

I'll try one more time.

At our company, we couldn't care less what code looks like on individual developers' laptops, only how it looks at rest in github. They're welcome to use any editor or IDE, and whatever format they prefer, while developing locally.

When they commit, we have a pre-commit hook that runs your fine Gradle plugin's formatter, ensuring that all Java files in the changeset are in canonical form. And then in Jenkins we run your plugin's verifier, in case someone didn't install the hook.

We have zero interest in pestering the developers before the point of commit. Actually, we have no interest in pestering the developers at all. We just want the formatting to happen before the PR is submitted, and automatically.

But because you run the format *check* by default in the build task, if developers don't remember to run goJF before building, it breaks their builds.

That's friction. It's pedantic. It makes no sense. Why would anyone want to inflict a manual step on their developers?

No sooner had I configured your plugin than one of our developers asked how to fix their build.

So, I configured it to always run the format task, and *then* build. Which works perfectly.

But I had to post on StackOverflow to find out how to do that, because it wasn't covered in your readme.

You say: "Task dependencies are a fundamental concept in Gradle and not specific to this plugin", which is technically true, but in that case, why did the first answer to my question on StackOverflow not work? (Reason: Because you named your extension the same as the format task.)

It would take you about three lines of text in your readme to tell all further users of your plugin how to run the formatter before running build, so they don't have to hunt for the answer on StackOverflow. 

You also said: "I don't see the point of having a verification task that can never fail". Have I explained that now?

**Comment by sherter** [comment]
If you don't want to fail the build, you should rather [ignore failures](https://docs.gradle.org/2.0/javadoc/org/gradle/api/tasks/VerificationTask.html#setIgnoreFailures(boolean)) in the verification task. There is an example for this in the readme (not in much detail, but as this is somehow also a 'standard' feature, good enough in my opinion). I guess you'd have to use an env variable or something like that to make the verification task fail the build (only) in CI.

When the verification task depends on the formatting task, the CI build will also format the code before verifying formatting. You'd never know that the submitted code was not formatted properly. I just don't see the point of that...

The verification task also doesn't really do anything if you run the formatting task before. The results of the format step are cached and reused in the verification phase (we know that if we just formatted something and the file wasn't touched afterwards, it must still be formatted correctly).

**Comment by jimshowalter** [comment]
That works.

**Comment by sherter** [comment]
So can I close this then or are you still convinced something should be documented?
