### ISSUE TITLE
Plugin fails with google-java-format 1.8

### ISSUE THREAD

**Issue by JamesGuthrie** [sherter/google-java-format-gradle-plugin#46]
When using this plugin with version 1.8 of google-java-format, the execution fails.

`build.gradle`:
```
plugins {
    id 'java'
    id 'com.github.sherter.google-java-format' version '0.8'
}
googleJavaFormat {
    toolVersion = '1.8'
}
```

`Gradle output`:
```
* What went wrong:
Execution failed for task ':googleJavaFormat'.
> Could not find matching constructor for: com.google.googlejavaformat.java.JavaFormatterOptions(com.google.googlejavaformat.java.JavaFormatterOptions$Style)
```

**Comment by sherter** [comment]
Thanks for the report. Commit 975a0591f808b05171626022cd3c36424520bbec adds support for google-java-format v1.8. A new release will follow soon.

**Comment by sherter** [comment]
Plugin version 0.9 with support for google-java-format v1.8 was released.
