### ISSUE TITLE
Configure default 'check' task to depend on verifyGoogleJavaFormat

### ISSUE THREAD

**Issue by tbroyer** [sherter/google-java-format-gradle-plugin#5]
The `check` task from the base plugin should be configured to depend on the created `verifyGoogleJavaFormat` task. I think 99% of the time, people will want to enforce that their sources follow the style rules, so that should be the default (just like when applying the `checkstyle`, `pmd` or `findbugs` plugin, they're run on `check` by default).

**Comment by sherter** [comment]
Yep, I thought about this before. I'm doing some refactoring right now, but as soon as I'm finished with that I'll add the dependsOn relationship. Thanks for the report!
