### ISSUE TITLE
Formatting field annotations on a separate lines relative to the field declaration

### ISSUE THREAD

**Issue by vardantandon** [sherter/google-java-format-gradle-plugin#51]
Hi team, 

After running the `./gradlew googleJavaFormat` I saw that field annotation were being clubbed together on a single line as the field declaration. For example,

**Before** `./gradlew googleJavaFormat`:

```java
@NotBlank
private final String username;
```

**After** `./gradlew googleJavaFormat`:

```java
@NotBlank private final String username;
```

Is there a way to configure the plugin such that this behaviour doesn't take place or annotations are placed on separate lines ?

Thanks !

**Comment by sherter** [comment]
No.
