### ISSUE TITLE
Java 17 with gradle 7 Support

### ISSUE THREAD

**Issue by schowave** [sherter/google-java-format-gradle-plugin#67]
Does this plugin support Java 17 with gradle 7? We used this plugin with Java 11 and gradle 6 and it worked very well. But with the upgrade to Java 17 and gradle 7, the plugin results in a build fail with the exception:

Detected Java syntax errors in the following files (you can exclude them from this task, see "https://github.com/sherter/google-java-format-gradle-plugin" for details):

<all Java classes> ...

--> I managed to workaround this, by using the spotless plugin https://github.com/diffplug/spotless

**Comment by aecio** [comment]
That error message is misleading. 

You should be able to use Java 17 by creating a file named `gradle.properties` in the root of your project with the following content:

```
org.gradle.jvmargs=--add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
```
Also, make sure to use a recent version of `google-java-format` that supports Java 17. It works for me using OpenJDK 17 and Gradle 7.2.

I created PR #66 to better describe the error.
