### ISSUE TITLE
Even after adding --add-exports, formatter fails on Java 17

### ISSUE THREAD

**Issue by jimshowalter** [sherter/google-java-format-gradle-plugin#70]
We have this configuration:

`org.gradle.jvmargs=--add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED`

`googleJavaFormatVersion=0.9`

`plugins {
    id "com.github.sherter.google-java-format" version "${googleJavaFormatVersion}"
}`

`apply plugin: 'com.github.sherter.google-java-format'`

`googleJavaFormat {
    exclude '**/wrapper/dists/**'
    exclude '**/src/generated/**'
}`

We're running Java 17:

`env | grep JAVA_HOME
JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
`

When we run ./gradlew googleJavaFormat, it does this:

`> Task :googleJavaFormat FAILED

Detected Java syntax errors in the following files (you can exclude them from this task, see "https://github.com/sherter/google-java-format-gradle-plugin" for details):

<list of every .java file in the repo>

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':googleJavaFormat'.
> Not all files were formatted.
`

**Comment by jimshowalter** [comment]
Needed to also set toolVersion.

**Comment by vnylbscr** [comment]
How can you solved problem? Can you write your build.gradle file here? I tried many times but it doesn't work for me.
