### ISSUE TITLE
Store channels not closed

### ISSUE THREAD

**Issue by sormuras** [sherter/google-java-format-gradle-plugin#9]
After an assemble run with gjfgp applied (`goFJ`) within Eclipse (buildship) on Windows, a following `clean` fails with:
```
Execution failed for task ':clean'.
> Unable to delete directory: [..]\build\google-java-format\0.4-SNAPSHOT
```
All files in the `0.4-SNAPSHOT` are locked - until Eclipse is closed.

Are the file channels not closed after use?
https://github.com/sherter/google-java-format-gradle-plugin/blob/master/src/main/java/com/github/sherter/googlejavaformatgradleplugin/FileInfoStore.java#L81
https://github.com/sherter/google-java-format-gradle-plugin/blob/master/src/main/java/com/github/sherter/googlejavaformatgradleplugin/FormatterOptionsStore.java#L62

**Comment by sherter** [comment]
That's a bug, thanks for reporting!

Can you try this [branch](https://github.com/sherter/google-java-format-gradle-plugin/tree/issue-9)?

**Comment by sormuras** [comment]
As the branch did not compile out-of-the-box in Eclipse, I can't. Any chance to release another 0.4-SNAPSHOT with the good-looking fix included?

**Comment by sherter** [comment]
> As the branch did not compile out-of-the-box in Eclipse, I can't.

Interesting. It might be a good idea to start using appveyor to test on windows infrastructure. I certainly would like to support windows and/or buildship (doesn't buildship use the gradle wrapper?).

How did you try to compile it? Can you try `gradlew publishToMavenLocal` from a cmd prompt and then use the following in your `build.gradle` to apply the plugin?

```groovy
buildscript {
    repositories {
        mavenLocal()
    }
    dependencies {
        classpath 'com.github.sherter.googlejavaformatgradleplugin:google-java-format-gradle-plugin:0.4-SNAPSHOT'
    }
}

apply plugin: 'com.github.sherter.google-java-format'
```


> Any chance to release another 0.4-SNAPSHOT with the good-looking fix included?

Sure! I merged the fix into master. The Snapshot should be available as soon as the travis build has finished.

**Comment by sormuras** [comment]
New snapshot releases the channel locks. :+1:

I just cloned the master branch and let Buildship add Gradle nature to the imported project. There was a "format" project visible, iirc, and compiler errors due to some `AutoValue` magic. I think, the annotation processor didn't kick in.
